[target.'cfg(all(target_arch = "arm", target_os = "none"))']
linker = "flip-link"
runner = "probe-rs run --chip STM32F303CCTx --connect-under-reset"
rustflags = ["-C", "link-arg=-Tdefmt.x"]

[build]
target = "thumbv7em-none-eabihf" # Cortex-M4F and Cortex-M7F (with FPU)
