# Perform a security audit.
# 
# This workflow ensures that the project dependencies are regularly audited for
# security vulnerabilities, providing an automated and consistent approach to
# maintaining the security of the project.
# 
# The workflow is triggered by:
# - A scheduled event that runs daily at midnight (UTC).
# - Manual dispatch.
#
# The workflow consists of a single job:
# 
# 1. **Audit**:
#    - Uses the rustsec/audit-check action to perform a security audit on the
#      Rust dependencies.
#    - The audit check action uses the GitHub token to authenticate requests.
# 
name: Security audit
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
